server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/togui
    driver-class-name: org.mariadb.jdbc.Driver
    username: togui
    password: togui1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

# jwt.secret.key 의 값은 256bit 이상이어야 한다.
jwt:
  secret:
    key: -JaNdRfUjXn2r5u8x/A?D(G+KbPeShVk